version: '3'
services:
  mongodb:
    container_name: mongo-coleta-api
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-coleta-seletiva
    build: .
    image: app-coleta-seletiva
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/coleta-seletiva-api/dist
    ports:
      - '3035:3035'
    links:
      - mongodb
